<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="SystemDesign\SplitWise\DTOs\" />
    <Folder Include="SystemDesign\SplitWise\Controller\" />
    <Folder Include="SystemDesign\SplitWise\Services\" />
    <Folder Include="SystemDesign\SplitWise\Repository\" />
  </ItemGroup>

</Project>
